apiVersion: v1
kind: ServiceAccount
metadata:
   name: {{ template "auth.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "auth.name" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  selector:
    app: {{ template "auth.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 5555
