kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "dex.name" . }}
data:
  config.yaml: |
    issuer: {{ .Values.config.issuer }}
    storage:
      type: postgres
      config:
        host: {{ template "dex.postgresql.fullname" . }}
        database: {{ .Values.config.database }}
        user: {{ .Values.config.user }}
        password: {{ .Values.config.password }}
        ssl:
          mode: disable
    web:
      http: 0.0.0.0:5556
      # https: 0.0.0.0:5556
      # tlsCert: /etc/dex/tls/tls.crt
      # tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        # TODO(tomgco) Move to k8s secrets
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: {{ .Values.config.dexRedirectURI }}
        orgs:
        - name: conde-nast-international
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: false
    staticClients:
    - id: k8s-auth
      redirectURIs:
{{ toYaml .Values.config.authRedirectURIs | indent 6 }}
      name: 'Kubernetes authentication'
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    expiry:
       signingKeys: "3h"
       idTokens: "12h"
    logger:
      level: "debug"
