apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dex.name" . }}
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{ .Release.Service }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "dex.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "dex.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "dex.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ template "dex.name" . }}
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 30000
        ports:
        - name: http
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls
        # TODO(tomgco) Move to secrets
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "dex.name" . }}-github
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "dex.name" . }}-github
              key: client-secret
      volumes:
      - name: config
        configMap:
          name: {{ template "dex.name" . }}
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: {{ template "dex.name" . }}-tls
