apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-auth-deployment
  labels:
    app: k8s-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auth
  template:
    metadata:
      labels:
        app: k8s-auth
    spec:
      serviceAccountName: k8s-auth
      containers:
      - image: quay.io/yldio/kubernetes-github-auth:1.1.5
        name: k8s-auth
        command: ["/usr/local/bin/k8s-auth", "--issuer", "https://dex.sandbox.yld.io", "--redirect-uri", "http://k8s-auth.sandbox.yld.io/callback", "--listen", "http://0.0.0.0:5555"]
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 30000
        ports:
        - name: http
          containerPort: 5555
