apiVersion: v1
kind: ServiceAccount
metadata:
   name: k8s-auth
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-auth
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: k8s-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5555
  type: LoadBalancer
